# Generated by Django 5.2.13 on 2026-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_alter_city_options_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
