# Generated by Django 5.2.13 on 2026-05-01 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_signuptohelpers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
        migrations.AddField(
            model_name='helperprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='availability',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='helpers.helperprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='helpers.helperprofile'),
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='services',
            field=models.ManyToManyField(blank=True, to='helpers.service'),
        ),
        migrations.AlterField(
            model_name='helperprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='helpers.specialty'),
        ),
        migrations.AlterField(
            model_name='signuptohelpers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
