# Generated by Django 5.2.13 on 2026-05-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_alter_availability_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptohelpers',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20),
        ),
    ]
