# Generated by Django 5.2.13 on 2026-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0008_alter_helperprofile_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='helpers/photos/'),
        ),
    ]
