# Generated by Django 5.2.13 on 2026-05-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seekerprofile'),
        ('helpers', '0008_alter_helperprofile_verification_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='helpers.helperprofile')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.seekerprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpers.service')),
            ],
            options={
                'ordering': ['-scheduled_date', '-scheduled_start_time'],
            },
        ),
    ]
